<a href="https://colab.research.google.com/github/mandywaeldchen/cgm-remote-monitor/blob/master/HbA1c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df=pd.read_excel('/content/drive/MyDrive/Workshop seaborn hbA1c/20210410_HbA1cAdults DIYAPS vs. nonDIYAPS.xlsx')

In [6]:
df.head()

   record_id  ...  selfreported_clin_out_diy_not_adults_12_complete
0          1  ...                                                 0
1          2  ...                                                 0
2          3  ...                                                 0
3          4  ...                                                 0
4          5  ...                                                 2

[5 rows x 44 columns]

In [7]:
df.describe()

         record_id  ...  selfreported_clin_out_diy_not_adults_12_complete
count  1052.000000  ...                                       1052.000000
mean    526.987643  ...                                          0.309886
std     304.263602  ...                                          0.724045
min       1.000000  ...                                          0.000000
25%     263.750000  ...                                          0.000000
50%     526.500000  ...                                          0.000000
75%     790.250000  ...                                          0.000000
max    1053.000000  ...                                          2.000000

[8 rows x 44 columns]